### ISSUE TITLE
add conversational memory for RAG

### ISSUE THREAD

**Issue by K-Schubert** [CdC-SI/ZAS-EAK-CopilotGPT#190]
**Description**

Store `k_memory` last messages (RAG+Autocomplete) in Redis DB and inject last `k_memory` conversation turns in chat prompt.

**Implementation**

- Setup Redis db service in `docker-compose.yml`
- Implement `store_message()` and `retrieve_conversation()` methods in `ConversationalMemory` `(chat/memory`)
    - stores with key `user:{user_uuid}:conversation:{conversation_uuid}:{message_uuid}`
        - store: `user_uuid`, `conversation_uuid`, `role`, `message`, `retrieved_docs`
    - retrieves with key `user:{user_uuid}:conversation:{conversation_uuid}:*`
- Inject last `k_memory` conversation turns (one turn is `user` query and `assistant` response) in chat prompt.
- Store history in `chat_history` postgres table in background using separate thread.
    - Index conversation history in postgres `chat_history` after each conversation turn.
- **Note: Currently only saves conversation turns for RAG, not Autocomplete**

**Comment by tabee** [comment]
> * --> Otherwise chat history might be "mixed" between users if multiple requests are made at the same time.

What you think about:

"Session-based Authentication" or "Token-based Session Management." Here is an overview of how you can implement it:

    Session ID Generation

When the app is opened, a random session ID is generated, e.g., a string of 5 letters. This session ID is displayed to the user and stored in the app.

    Storing Chat Data

The chat data is stored in a database under the generated session ID. Each chat message is linked to this session ID.

    Loading an Existing Session

If a user wants to load an existing session, they enter the 5-letter session ID. The app then loads the corresponding chat data from the database.
